compatibility_matrix:
  versions:
      - rocm_version: "6.4.0"
        file: rocm-60400-compute-compatibility.yaml
      - rocm_version: "6.3.3"
        file: rocm-60303-compute-compatibility.yaml
      - rocm_version: "6.3.2"
        file: rocm-60302-compute-compatibility.yaml
      - rocm_version: "6.3.1"
        file: rocm-60301-compute-compatibility.yaml
      - rocm_version: "6.3.0"
        file: rocm-60300-compute-compatibility.yaml
      - rocm_version: "6.2.4"
        file: rocm-60204-compute-compatibility.yaml
  template_config:
